apiVersion: apps/v1
kind: DaemonSet
metadata:
      name: ds
spec:
     template: # template from pod.yml
       metadata:
            name: ds1
            labels:
              name: xyz
       spec:
         containers:
            - name: ds1
              image: nginx

     selector:
      matchLabels:
         name: xyz
