apiVersion: v1
kind: Pod
metadata:
  name: database
  labels: 
    name: db  
spec:
  containers:
  - name: database1
    image: mysql                # creating pod from mysql image

    env:                        # setting environment variable for mysql for secure login by providing root password for database
        - name: MYSQL_ROOT_PASSWORD     # key of your env variable
          valueFrom:
                  configMapKeyRef:
                          name: cm1     # name of configMap   
                          key: MYSQL_ROOT_PASSWORD # configMap key and value will be fetch automatically
          
