apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels: 
  name: host-volume-attached-pod
spec:
  containers:
  - name: volume-pod
    image: nginx
  
  
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  volumes: 
     - name: my-volume
       hostPath: 
             path: /home/sanjaykumaratal18/my-backup    # Specify the path of directory created on host system to store backup 
             type: DirectoryOrCreate          # use to create Directory on node where our pod is deployed , no need to specify the directory on each node
