apiVersion: v1
kind: Service
metadata:
  name: my-nginx-load-balancer
spec:
  selector:
    app: my-nginx-app
  ports:
  - name: http
    port: 80		# port associate with cluster ip
    targetPort: 80	# container/pod port
  type: LoadBalancer
  externalIPs:
     - 35.188.11.2	# mention your external/public/static IP provided by your cloud provider like AWS, GCP, Azure

