apiVersion: apps/v1
kind: Deployment
metadata:
      name: testing-cluster-ip
spec:
     template: # template from pod.yml
       metadata:
            name: web2
            labels:
              name: xyz
       spec:
         containers:
            - name: web
              image: nginx

     selector:
      matchLabels:
         name: xyz # provide this label to clstripsrvc.yml
     replicas: 3      # number of replicas to create
