apiVersion: v1
kind: Service
metadata:
  labels:
    app: myclusteripservice
  name: myclusteripservice
spec:
  ports:
  - name: "clusteripservice"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: xyz
  type: ClusterIP
