apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nodeport-service
  name: my-nodeport-service
spec:
  ports:
  - name: "nodeport-service"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    name: xyz
  type: NodePort
