apiVersion: v1
kind: Pod
metadata:
  name: database
  labels: 
    name: db  
spec:
  containers:
  - name: database1
    image: mysql                # creating pod from mysql image
    resources:                  
      requests:
        memory: "500M"          # you can skip resource limit if not use quota,yml on a namespace
        cpu: "500m"
      limits:
        memory: "500M"
        cpu: "500m"

    env:                        # setting environment variable for mysql for secure login by providing root password for database
        - name: MYSQL_ROOT_PASSWORD
          value: admin    
