apiVersion: v1
kind: ReplicationController
metadata:
      name: web-app-rc
spec:
     template: # template from pod.yml
       metadata:
            name: web2
            labels:
              name: xyz
       spec:
         containers:
            - name: web
              image: nginx

     selector:
         name: xyz
     replicas: 3      # number of replicas to create
