apiVersion: v1
kind: Service
metadata:
  labels:
    app: myclustersvc
  name: myclustersvc
spec:
  ports:
  - name: "svc1"
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
          name: xyz 
  type: ClusterIP
