apiVersion: v1
kind: Service
metadata:
  labels:
    app: mynpsvc
  name: mynpsvc
spec:
  ports:
  - name: "svc1"
    port: 80
    nodePort: 30011 
    protocol: TCP
    targetPort: 80
  selector:
          name: xyz 
  type: NodePort
