apiVersion: v1
kind: Pod
metadata:
  name: web4
  labels: 
    name: label2  
spec:
  containers:
  - name: web4
    image: nginx
  tolerations:
          - key: env
            operator: "Equal"
            effect: "NoSchedule"
