apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels: 
  name: volume-attached-pod
spec:
  containers:
  - name: volume-pod
    image: nginx
  
  
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: my-volume
  volumes: 
     - name: my-volume
       emptyDir:
